server/__init__.py
import os
import logging

from flask import Flask, render_template, g, request
from flask_rq import RQ
from webassets.loaders import PythonLoader as PythonAssetsLoader
from werkzeug.contrib.fixers import ProxyFix

from server import assets, converters, utils
from server.forms import CSRFForm
from server.models import db
from server.controllers.about import about
from server.controllers.admin import admin
from server.controllers.api import endpoints as api_endpoints
from server.controllers.api import api  # Flask Restful API
from server.controllers.auth import auth, login_manager
from server.controllers.oauth import oauth
from server.controllers.student import student
from server.controllers.queue import queue
from server.controllers.files import files
from server.constants import API_PREFIX

from server.extensions import (
    assets_env,
    cache,
    csrf,
    debug_toolbar,
    sentry,
    storage
)

def create_app(default_config_path=None):
    """Create and return a Flask application. Reads a config file path from the
    OK_SERVER_CONFIG environment variable. If it is not set, reads from
    default_config_path instead. This is so we can default to a development
    environment locally, but the app will fail in production if there is no
    config file rather than dangerously defaulting to a development environment.
    """

    app = Flask(__name__)

    config_path = os.getenv('OK_SERVER_CONFIG', default_config_path)
    if config_path is None:
        raise ValueError('No configuration file found'
            'Check that the OK_SERVER_CONFIG environment variable is set.')
    app.config.from_pyfile(config_path)

    # Senty Error Reporting & Other Prod Changes
    sentry_dsn = os.getenv('SENTRY_DSN')
    if not app.debug:
        app.wsgi_app = ProxyFix(app.wsgi_app)
        if sentry_dsn:
            sentry.init_app(app, dsn=sentry_dsn)

            @app.errorhandler(500)
            def internal_server_error(error):
                return render_template('errors/500.html',
                    event_id=g.sentry_event_id,
                    public_dsn=sentry.client.get_public_dsn('https')
                ), 500

        # In production mode, add log handler to sys.stderr.
        app.logger.addHandler(logging.StreamHandler())
        app.logger.setLevel(logging.INFO)

    @app.errorhandler(404)
    def not_found_error(error):
        if request.path.startswith("/api"):
            return api.handle_error(error)
        return render_template('errors/404.html'), 404

    # initialize the cache
    cache.init_app(app)

    # initialize redis task queues
    RQ(app)

    # Protect All Routes from csrf
    csrf.init_app(app)

    # initialize the debug tool bar
    debug_toolbar.init_app(app)

    # initialize SQLAlchemy
    db.init_app(app)

    # Flask-Login manager
    login_manager.init_app(app)

    # initalize cloud storage
    storage.init_app(app)

    # Import and register the different asset bundles
    assets_env.init_app(app)
    assets_loader = PythonAssetsLoader(assets)
    for name, bundle in assets_loader.load_bundles().items():
        assets_env.register(name, bundle)

    # custom URL handling
    converters.init_app(app)

    # custom Jinja rendering
    app.jinja_env.globals.update({
        'utils': utils,
        'debug': app.debug,
        'instantclick': app.config.get('INSTANTCLICK', True),
        'CSRFForm': CSRFForm
    })

    app.jinja_env.filters.update({
        'markdown': utils.convert_markdown,
        'pluralize': utils.pluralize,
    })

    # register our blueprints
    # OAuth should not need CSRF protection
    csrf.exempt(auth)
    app.register_blueprint(auth)

    csrf.exempt(oauth)
    app.register_blueprint(oauth)
    app.register_blueprint(files)

    app.register_blueprint(student)

    app.register_blueprint(admin, url_prefix='/admin')
    app.register_blueprint(about, url_prefix='/about')

    # Redis Queue dashboard
    csrf.exempt(queue)
    app.register_blueprint(queue, url_prefix='/rq')

    # API does not need CSRF protection
    csrf.exempt(api_endpoints)
    app.register_blueprint(api_endpoints, url_prefix=API_PREFIX)

    return app

server/app/apiclient/__init__.py
"""Retain apiclient as an alias for googleapiclient."""

from six import iteritems

import googleapiclient

try:
  import oauth2client
except ImportError:
  raise RuntimeError(
      'Previous version of google-api-python-client detected; due to a '
      'packaging issue, we cannot perform an in-place upgrade. To repair, '
      'remove and reinstall this package, along with oauth2client and '
      'uritemplate. One can do this with pip via\n'
      '  pip install -I google-api-python-client'
  )

from googleapiclient import channel
from googleapiclient import discovery
from googleapiclient import errors
from googleapiclient import http
from googleapiclient import mimeparse
from googleapiclient import model
from googleapiclient import sample_tools
from googleapiclient import schema

__version__ = googleapiclient.__version__

_SUBMODULES = {
    'channel': channel,
    'discovery': discovery,
    'errors': errors,
    'http': http,
    'mimeparse': mimeparse,
    'model': model,
    'sample_tools': sample_tools,
    'schema': schema,
}

import sys
for module_name, module in iteritems(_SUBMODULES):
  sys.modules['apiclient.%s' % module_name] = module

server/app/googleapiclient/__init__.py
# Copyright 2014 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

__version__ = "1.4.2"

server/app/googleapiclient/discovery_cache/__init__.py
# Copyright 2014 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Caching utility for the discovery document."""

from __future__ import absolute_import

import logging
import datetime

DISCOVERY_DOC_MAX_AGE = 60 * 60 * 24  # 1 day


def autodetect():
  """Detects an appropriate cache module and returns it.

  Returns:
    googleapiclient.discovery_cache.base.Cache, a cache object which
    is auto detected, or None if no cache object is available.
  """
  try:
    from google.appengine.api import memcache
    from . import appengine_memcache
    return appengine_memcache.cache
  except Exception:
    try:
      from . import file_cache
      return file_cache.cache
    except Exception as e:
      logging.warning(e, exc_info=True)
      return None

server/controllers/about.py
from flask import Blueprint, render_template

about = Blueprint('about', __name__)

@about.route('/privacy/')
def privacy():
    return render_template('about/privacy.html')

server/controllers/admin.py
import collections
import csv
from functools import wraps
from io import StringIO

from flask import (Blueprint, render_template, flash, redirect, Response,
                   url_for, abort, request, stream_with_context)
from werkzeug.exceptions import BadRequest

from flask_login import current_user, login_required
import pygal
from pygal.style import CleanStyle
import requests.exceptions

from server import autograder

import server.controllers.api as ok_api
from server.models import (User, Course, Assignment, Enrollment, Version,
                           GradingTask, Backup, Score, Group, Client, Job,
                           Message, CanvasCourse, CanvasAssignment, db)
from server.constants import (INSTRUCTOR_ROLE, STAFF_ROLES, STUDENT_ROLE,
                              LAB_ASSISTANT_ROLE, SCORE_KINDS)

import server.canvas.api as canvas_api
import server.canvas.upload
from server.extensions import cache
import server.forms as forms
import server.jobs as jobs
import server.jobs.example as example
import server.jobs.moss as moss
import server.jobs.github_search as github_search

import server.highlight as highlight
import server.utils as utils

admin = Blueprint('admin', __name__)

def is_staff(course_arg=None):
    """ A decorator for routes to ensure that user is a member of
    the course staff.

    Usage:
    @is_staff() - A staff member for any course
    @is_staff(course_arg=1) A staff member for the course with id 1
    """
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            if current_user.is_authenticated:
                if current_user.is_admin:
                    return func(*args, **kwargs)
                roles = current_user.enrollments(roles=STAFF_ROLES)
                if len(roles) > 0:
                    if course_arg:
                        course = kwargs[course_arg]
                        if course in [r.course.id for r in roles]:
                            return func(*args, **kwargs)
                    else:
                        return func(*args, **kwargs)
            else:
                return redirect(url_for("student.index"))
            flash("You are not on the course staff", "error")
            return redirect(url_for("student.index"))
        return login_required(wrapper)
    return decorator


def get_courses(cid=None):
    if current_user.is_authenticated and current_user.is_admin:
        courses = (Course.query.order_by(Course.created.desc())
                         .all())
    else:
        enrollments = current_user.enrollments(roles=STAFF_ROLES)
        courses = [e.course for e in enrollments]
    if not cid:
        return courses, []

    matching_courses = [c for c in courses if c.id == cid]
    if len(matching_courses) == 0:
        abort(401)
    current_course = matching_courses[0]
    return courses, current_course


@admin.route("/")
@is_staff()
def index():
    courses, current_course = get_courses()
    if courses:
        return redirect(url_for(".course_assignments", cid=courses[0].id))
    return render_template('staff/index.html', courses=courses)

@admin.route('/grading')
@is_staff()
def grading_tasks(username=None):
    courses, current_course = get_courses()
    page = request.args.get('page', 1, type=int)
    tasks_query = GradingTask.query.filter_by(grader=current_user)
    queue = (tasks_query.options(db.joinedload('assignment'))
                        .order_by(GradingTask.score_id.asc())
                        .order_by(GradingTask.created.asc())
                        .paginate(page=page, per_page=20))

    remaining = tasks_query.filter_by(score_id=None).count()
    percent_left = (1-(remaining/max(1, queue.total))) * 100
    return render_template('staff/grading/queue.html', courses=courses,
                           queue=queue, remaining=remaining,
                           percent_left=percent_left)

def grading_view(backup, form=None, is_composition=False):
    """ General purpose grading view. Used by routes."""
    courses, current_course = get_courses()
    assign = backup.assignment
    diff_type = request.args.get('diff')
    if diff_type not in (None, 'short', 'full'):
        diff_type = None
    if not assign.files and diff_type:
        diff_type = None

    # sort comments by (filename, line)
    comments = collections.defaultdict(list)
    for comment in backup.comments:
        comments[(comment.filename, comment.line)].append(comment)

    # highlight files and add comments
    files = highlight.diff_files(assign.files, backup.files(), diff_type)
    for filename, source_file in files.items():
        for line in source_file.lines:
            line.comments = comments[(filename, line.line_after)]

    group = [User.query.get(o) for o in backup.owners()]
    task = backup.grading_tasks
    if task:
        # Choose the first grading_task
        task = task[0]

    return render_template(
        'staff/grading/code.html', courses=courses, assignment=assign,
        backup=backup, group=group, files=files,
        diff_type=diff_type, task=task, form=form, is_composition=is_composition
    )

@admin.route('/grading/<hashid:bid>')
@is_staff()
def grading(bid):
    backup = Backup.query.get(bid)
    if not (backup and Backup.can(backup, current_user, "grade")):
        abort(404)

    form = forms.GradeForm()
    existing = [s for s in backup.scores if not s.archived]
    first_score = existing[0] if existing else None

    if first_score and first_score.kind in SCORE_KINDS:
        form = forms.GradeForm(kind=first_score.kind)
        form.kind.data = first_score.kind
        form.message.data = first_score.message
        form.score.data = first_score.score

    return grading_view(backup, form=form)

@admin.route('/composition/<hashid:bid>')
@is_staff()
def composition(bid):
    backup = Backup.query.get(bid)
    if not (backup and Backup.can(backup, current_user, "grade")):
        abort(404)
    form = forms.CompositionScoreForm()
    existing = Score.query.filter_by(backup=backup, kind="composition").first()
    if existing:
        form.kind.data = "composition"
        form.message.data = existing.message
        form.score.data = existing.score
    return grading_view(backup, form=form, is_composition=True)

@admin.route('/grading/<hashid:bid>/edit', methods=['GET', 'POST'])
@is_staff()
def edit_backup(bid):
    courses, current_course = get_courses()
    backup = Backup.query.options(db.joinedload('assignment')).get(bid)
    if not backup:
        abort(404)
    if not Backup.can(backup, current_user, 'grade'):
        flash("You do not have permission to score this assignment.", "warning")
        abort(401)
    form = forms.SubmissionTimeForm()
    if form.validate_on_submit():
        backup.custom_submission_time = form.get_submission_time(backup.assignment)
        db.session.commit()
        flash('Submission time saved', 'success')
        return redirect(url_for('.edit_backup', bid=bid))
    else:
        form.set_submission_time(backup)
    return render_template(
        'staff/grading/edit.html',
        courses=courses,
        current_course=current_course,
        backup=backup,
        student=backup.submitter,
        form=form,
    )

@admin.route('/grading/<hashid:bid>/grade', methods=['POST'])
@is_staff()
def grade(bid):
    """ Used as a form submission endpoint. """
    backup = Backup.query.options(db.joinedload('assignment')).get(bid)
    if not backup:
        abort(404)
    if not Backup.can(backup, current_user, 'grade'):
        flash("You do not have permission to score this assignment.", "warning")
        abort(401)

    form = forms.GradeForm()
    score_kind = form.kind.data.strip().lower()
    is_composition = (score_kind == "composition")
    # TODO: Form should include redirect url instead of guessing based off tag

    if is_composition:
        form = forms.CompositionScoreForm()

    if not form.validate_on_submit():
        return grading_view(backup, form=form)

    score = Score(backup=backup, grader=current_user,
                  assignment_id=backup.assignment_id, user_id=backup.submitter_id)
    form.populate_obj(score)
    db.session.add(score)
    db.session.commit()

    # Archive old scores of the same kind
    score.archive_duplicates()

    next_page = None
    flash_msg = "Added a {0} {1} score.".format(score.score, score_kind)

    # Find GradingTasks applicable to this score
    tasks = backup.grading_tasks
    for task in tasks:
        task.score = score
        cache.delete_memoized(User.num_grading_tasks, task.grader)

    db.session.commit()

    if len(tasks) == 1:
        # Go to next task for the current task queue if possible.
        task = tasks[0]
        next_task = task.get_next_task()
        next_route = '.composition' if is_composition else '.grading'
        # Handle case when the task is on the users queue
        if next_task:
            flash_msg += (" There are {0} tasks left. Here's the next submission:"
                          .format(task.remaining))
            next_page = url_for(next_route, bid=next_task.backup_id)
        else:
            flash_msg += " All done with grading for {}".format(backup.assignment.name)
            next_page = url_for('.grading_tasks')
    else:
        # TODO: Send task id or redirect_url in the grading form
        # For now, default to grading tasks
        next_page = url_for('.grading_tasks')

    flash(flash_msg, 'success')

    if not next_page:
        next_page = url_for('.assignment_queues', aid=backup.assignment_id,
                            cid=backup.assignment.course_id)
    return redirect(next_page)

@admin.route('/grading/<hashid:bid>/autograde', methods=['POST'])
@is_staff()
def autograde_backup(bid):
    backup = Backup.query.options(db.joinedload('assignment')).get(bid)
    if not backup:
        abort(404)
    if not Backup.can(backup, current_user, 'grade'):

server/controllers/queue.py
from flask import abort, current_app
from flask_login import current_user
import rq_dashboard

from server import jobs

queue = rq_dashboard.blueprint

@queue.before_request
def authenticate(*args, **kwargs):
    if not current_user.is_authenticated:
        return current_app.login_manager.unauthorized()
    if not current_user.is_admin:
        abort(403)

server/templates/staff/student/assignment.graph.html
{% extends "staff/base.html" %}
{% import 'diff.html' as diff with context %}
{% import 'staff/_formhelpers.html' as forms %}

{% block title %} {{assignment.display_name}} Diff Graph {% endblock %}

{% block main %}
<style> .pygal-chart {max-height: 1000px !important;} </style>
<section class="content-header">
    <h1>
        {{ assignment.display_name }} Diff Graph
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ url_for(".index") }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="{{ url_for(".course", cid=assignment.course.id) }}">
            <i class="fa fa-university"></i> {{ assignment.course.offering }}
        </a></li>
        <li><a href="{{ url_for('.course_assignments', cid=assignment.course.id) }}">
          <i class="fa fa-list"></i> Assignments</a>
        </li>
        <li class="active"><a href="{{ url_for('.assignment', cid=assignment.course.id, aid=assignment.id) }}"><i class="fa fa-book"></i> {{ assignment.display_name }}</a></li>
    </ol>
</section>

<section class="content">
    {% include 'alerts.html' %}

    <!-- Default box -->
    <!-- Content Box -->
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <div class="box box-default collapsed-box">
                <div class="box-header with-border">
                    <h3 class="box-title">Submitter Information</h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i>
                        </button>
                    </div>
                    <!-- /.box-tools -->
                </div>
                <!-- /.box-header -->
                <div class="box-body" class="spoiler">
                    {% if group %}
                        <br>
                        Group:
                        {% for member in group %}
                            <a>
                               {{ member.email }}
                            </a>
                        {% endfor %}
                        <br>
                    {% endif %}
                </div>
                <!-- /.box-body -->
            </div>
        </div>
        <div class="col-md-6 col-xs-12">
            <!-- /.box -->
            <div class="box collapsed-box">
                <div class="box-header with-border">
                    <h3 class="box-title">Scores ({{ scores | length }}) </h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i>
                        </button>
                    </div>
                    <!-- /.box-tools -->
                </div>
                <!-- /.box-header -->
                <div class="box-body no-padding" class="spoiler" style="display: none;">
                    <ul class="nav nav-pills nav-stacked" >
                        {% if not scores %}
                        <li><a href="#"><b> No Scores </b> <span class="pull-right text-red">Ungraded</span></a></li>
                        {% else %}
                        {% for score in scores %}
                            <li><a href="#"><b>{{ score.kind }}</b>: "{{ score.message | truncate(20) }}" from {{ score.grader.email }}
                                <span class="pull-right text-{{ 'green' if score.public else 'red' }}">{{ score.score | round(3) }} </span>
                                </a>
                            </li>
                        {% endfor %}
                        {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /.widget-user -->
        </div>

        <div class="box-body">
            <div class="row">
                {% for graph in graphs %}
                    <div class="col-xs-12">
                        {{ graph.render() | safe }}
                    </div>
                {% endfor %}
            </div>
        </div>

        <!-- </section> do not close the content section -->

        <!-- </body> do not close body in template-->
        {% endblock %}

server/templates/staff/student/assignment.list.html
{% import 'staff/_helpers.html' as helpers %}

<div class="box">
    <div class="box-header">
        <h3 class="box-title"><span> {{ title }} Assignments </span></h3>
        <div class="box-tools">
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
    </div>

    <!-- /.box-header -->
    <div class="box-body table-responsive no-padding table-loading" id="{{ title }}-list">
        <table class="table table-hover">
            <thead>
                <th class="sort" data-sort="assignment">Assignment</th>
                <th class="sort" data-sort="due-date">Due Date</th>
                <th class="sort" data-sort="group">Group</th>
                <th class="sort" data-sort="submission-time">Time Submitted</th>
                <th>Final Submission</th>
                <th class="sort" data-sort="scores">Scores</th>
                <th>Actions</th>
            </thead>

            <tbody class="list">
                {%- for item in assignments %}
                <tr>
                    <td class="assignment"><a href="{{url_for('.student_assignment_detail', cid=current_course.id, email=student.email, aid=item.assignment.id)}}">{{ item.assignment.display_name }}</a></td>
                    <td class="due-date" data-timestamp="{{ item.assignment.due_date }}">{{ utils.local_time(item.assignment.due_date, current_course) }}
                    </td>
                    <td class="group">
                    {% if item.group %}
                        {% for member in item.group.members %}
                            {% if member.user.email != student.email %}
                                {% if member.status == 'active' %}
                                    <i class="fa fa-check-circle-o text-green" alt="Active Member"></i>
                                {% else %}
                                    <i class="fa fa-envelope text-gray" alt="Active Member"></i>
                                {% endif %}
                                <a href="{{ url_for('.student_view', cid=current_course.id, email=member.user.email) }}">{{ member.user.identifier }}</a>
                                <br>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        <i class="fa fa-user-times text-gray" aria-hidden="true"></i>
                    {% endif %}

                    </td>

                    {% if item.subm_time %}
                        <td class="submission-time" data-timestamp="{{ item.created }}" data-timestamp="{{ item.subm_time }}">{{ utils.local_time(item.subm_time, current_course) }}
                        </td>
                        <td class="final-subm-id">
                            {{ helpers.backup_link(item.final_subm.id) }}
                        </td>
                    {% else %}
                        <td class="submission-time" data-timestamp="{{ item.created }}">No Submission
                        </td>
                        <td class="final-subm-id">
                            <i class="fa fa-times-circle text-red" aria-hidden="true"></i>
                        </td>

                    {% endif %}
                    <td class="scores">
                      {{ helpers.score_pills(item.scores) }}
                    </td>
                    <td >
                        <a href="{{url_for('.student_assignment_detail', cid=current_course.id, email=student.email, aid=item.assignment.id)}}">
                            <button class="btn btn-xs btn-default btn-plain"> Details </button>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- /.box-body -->
    <div class="box-footer">
        <div class="pull-left">
        <h5 class="box-title"><span> Total: {{ assignments | length }} </span></h5>
        </div>
    </div>

</div>

server/templates/staff/student/overview.html
{% extends "staff/base.html" %}

{% block title %} {{ student.identifier }} - {{ current_course.display_name_with_semester }}{% endblock %}

{% block main %}
  <section class="content-header">
      <h1>
        {{ student.email }}
        <small> {{ current_course.display_name }}</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{ url_for("admin.index") }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="{{ url_for("admin.course", cid=current_course.id) }}">
            <i class="fa fa-university"></i> {{ current_course.offering }}
        </a></li>
        <li class="active"><a href="{{ url_for('.enrollment', cid=current_course.id) }}">
            <i class="fa fa-list"></i> Enrollment</a>
        </li>
        <li class="active"><a href="#"><i class="fa fa-dashboard"></i> {{ student.email }} </a></li>
      </ol>
  </section>

  <section class="content">
      {% include 'alerts.html' %}
      <div class="row">
        <div class="col-md-12">
          <div class="box box-widget widget-user-2">
            <div class="widget-user-header bg-yellow">
             <div class="widget-user-image">
                <img class="img-circle bg-green">
              </div>

             <!-- /.widget-user-image -->
              <h3 class="widget-user-username">{{ student.identifier }}</h3>
              <h5 class="widget-user-desc"> {{ student.role | capitalize }}</h5>
            </div>
            <div class="box-footer no-padding">
              <ul class="nav nav-stacked">
                {% if enrollment %}

                    {% if enrollment.sid %}
                    <li>
                      <a href="#">Student ID <span class="pull-right badge bg-blue">{{ enrollment.sid }}</span></a>
                    </li>
                    {% endif %}
                    {% if enrollment.class_account %}
                    <li>
                      <a href="#">Course Account <span class="pull-right badge bg-aqua">
                      {{ enrollment.class_account }}
                      </span></a>
                    </li>
                    {% endif %}
                    <li>
                      <a href="#">Role <span class="pull-right badge bg-red">
                      {{ enrollment.role }}
                      </span></a>
                    </li>
                    <li>
                      <a href="#">Enrolled At <span class="pull-right badge bg-green">
                            {{ utils.local_time(enrollment.created, current_course) }}
                      </span></a>
                    </li>
                {% else %}
                <li>
                  <a href="{{ url_for('.enrollment', cid=current_course.id) }}">
                  Status: <span class="pull-right badge bg-red">
                  Not Enrolled
                  </span></a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
          <!-- /.widget-user -->
        </div>
      </div>


      <div class="row">
        <div class="col-md-12">
          {% with assignments=assignments['active'], title='Active' %}
            {% include 'staff/student/assignment.list.html' %}
          {% endwith %}

          {% with assignments=assignments['inactive'], title='Inactive' %}
            {% include 'staff/student/assignment.list.html' %}
          {% endwith %}
        </div>
      </div>
  </section>

  <!-- </body> do not close body in template-->
{% endblock %}

{% block page_js %}
{% endblock %}