server/__init__.py
import os
import logging

from flask import Flask, render_template, g, request
from flask_rq import RQ
from webassets.loaders import PythonLoader as PythonAssetsLoader
from werkzeug.contrib.fixers import ProxyFix

from server import assets, converters, utils
from server.forms import CSRFForm
from server.models import db
from server.controllers.about import about
from server.controllers.admin import admin
from server.controllers.api import endpoints as api_endpoints
from server.controllers.api import api  # Flask Restful API
from server.controllers.auth import auth, login_manager
from server.controllers.oauth import oauth
from server.controllers.student import student
from server.controllers.queue import queue
from server.controllers.files import files
from server.constants import API_PREFIX

from server.extensions import (
    assets_env,
    cache,
    csrf,
    debug_toolbar,
    sentry,
    storage
)

def create_app(default_config_path=None):
    """Create and return a Flask application. Reads a config file path from the
    OK_SERVER_CONFIG environment variable. If it is not set, reads from
    default_config_path instead. This is so we can default to a development
    environment locally, but the app will fail in production if there is no
    config file rather than dangerously defaulting to a development environment.
    """

    app = Flask(__name__)

    config_path = os.getenv('OK_SERVER_CONFIG', default_config_path)
    if config_path is None:
        raise ValueError('No configuration file found'
            'Check that the OK_SERVER_CONFIG environment variable is set.')
    app.config.from_pyfile(config_path)

    # Senty Error Reporting & Other Prod Changes
    sentry_dsn = os.getenv('SENTRY_DSN')
    if not app.debug:
        app.wsgi_app = ProxyFix(app.wsgi_app)
        if sentry_dsn:
            sentry.init_app(app, dsn=sentry_dsn)

            @app.errorhandler(500)
            def internal_server_error(error):
                return render_template('errors/500.html',
                    event_id=g.sentry_event_id,
                    public_dsn=sentry.client.get_public_dsn('https')
                ), 500

        # In production mode, add log handler to sys.stderr.
        app.logger.addHandler(logging.StreamHandler())
        app.logger.setLevel(logging.INFO)

    @app.errorhandler(404)
    def not_found_error(error):
        if request.path.startswith("/api"):
            return api.handle_error(error)
        return render_template('errors/404.html'), 404

    # initialize the cache
    cache.init_app(app)

    # initialize redis task queues
    RQ(app)

    # Protect All Routes from csrf
    csrf.init_app(app)

    # initialize the debug tool bar
    debug_toolbar.init_app(app)

    # initialize SQLAlchemy
    db.init_app(app)

    # Flask-Login manager
    login_manager.init_app(app)

    # initalize cloud storage
    storage.init_app(app)

    # Import and register the different asset bundles
    assets_env.init_app(app)
    assets_loader = PythonAssetsLoader(assets)
    for name, bundle in assets_loader.load_bundles().items():
        assets_env.register(name, bundle)

    # custom URL handling
    converters.init_app(app)

    # custom Jinja rendering
    app.jinja_env.globals.update({
        'utils': utils,
        'debug': app.debug,
        'instantclick': app.config.get('INSTANTCLICK', True),
        'CSRFForm': CSRFForm
    })

    app.jinja_env.filters.update({
        'markdown': utils.convert_markdown,
        'pluralize': utils.pluralize,
    })

    # register our blueprints
    # OAuth should not need CSRF protection
    csrf.exempt(auth)
    app.register_blueprint(auth)

    csrf.exempt(oauth)
    app.register_blueprint(oauth)
    app.register_blueprint(files)

    app.register_blueprint(student)

    app.register_blueprint(admin, url_prefix='/admin')
    app.register_blueprint(about, url_prefix='/about')

    # Redis Queue dashboard
    csrf.exempt(queue)
    app.register_blueprint(queue, url_prefix='/rq')

    # API does not need CSRF protection
    csrf.exempt(api_endpoints)
    app.register_blueprint(api_endpoints, url_prefix=API_PREFIX)

    return app

server/app/apiclient/__init__.py
"""Retain apiclient as an alias for googleapiclient."""

from six import iteritems

import googleapiclient

try:
  import oauth2client
except ImportError:
  raise RuntimeError(
      'Previous version of google-api-python-client detected; due to a '
      'packaging issue, we cannot perform an in-place upgrade. To repair, '
      'remove and reinstall this package, along with oauth2client and '
      'uritemplate. One can do this with pip via\n'
      '  pip install -I google-api-python-client'
  )

from googleapiclient import channel
from googleapiclient import discovery
from googleapiclient import errors
from googleapiclient import http
from googleapiclient import mimeparse
from googleapiclient import model
from googleapiclient import sample_tools
from googleapiclient import schema

__version__ = googleapiclient.__version__

_SUBMODULES = {
    'channel': channel,
    'discovery': discovery,
    'errors': errors,
    'http': http,
    'mimeparse': mimeparse,
    'model': model,
    'sample_tools': sample_tools,
    'schema': schema,
}

import sys
for module_name, module in iteritems(_SUBMODULES):
  sys.modules['apiclient.%s' % module_name] = module

server/app/googleapiclient/__init__.py
# Copyright 2014 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

__version__ = "1.4.2"

server/app/googleapiclient/discovery_cache/__init__.py
# Copyright 2014 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Caching utility for the discovery document."""

from __future__ import absolute_import

import logging
import datetime

DISCOVERY_DOC_MAX_AGE = 60 * 60 * 24  # 1 day


def autodetect():
  """Detects an appropriate cache module and returns it.

  Returns:
    googleapiclient.discovery_cache.base.Cache, a cache object which
    is auto detected, or None if no cache object is available.
  """
  try:
    from google.appengine.api import memcache
    from . import appengine_memcache
    return appengine_memcache.cache
  except Exception:
    try:
      from . import file_cache
      return file_cache.cache
    except Exception as e:
      logging.warning(e, exc_info=True)
      return None

server/controllers/about.py
from flask import Blueprint, render_template

about = Blueprint('about', __name__)

@about.route('/privacy/')
def privacy():
    return render_template('about/privacy.html')

server/controllers/auth.py
"""
There are two ways to authenticate a request:
* Present the session cookie returned after logging in
* Send a Google access token as the access_token query parameter
"""
from flask import (abort, Blueprint, current_app, flash, redirect,
                   render_template, request, session, url_for, jsonify)
from flask_oauthlib.client import OAuth, OAuthException
from flask_oauthlib.contrib.oauth2 import bind_sqlalchemy

from flask_login import (LoginManager, login_user, logout_user, login_required,
                         current_user)
import requests

import datetime as dt
import logging

from server import utils
from server.models import db, User, Enrollment, Client, Token, Grant
from server.extensions import csrf, oauth_provider, cache

logger = logging.getLogger(__name__)

auth = Blueprint('auth', __name__)

auth.config = {}

@auth.record
def record_params(setup_state):
    """ Load used app configs into local config on registration from
    server/__init__.py """
    app = setup_state.app
    oauth.init_app(app)

oauth = OAuth()
google_auth = oauth.remote_app(
    'google',
    app_key='GOOGLE',
    request_token_params={
        'scope': 'email',
        'prompt': 'select_account'
    },
    base_url='https://www.googleapis.com/oauth2/v3/',
    request_token_url=None,
    access_token_method='POST',
    access_token_url='https://accounts.google.com/o/oauth2/token',
    authorize_url='https://accounts.google.com/o/oauth2/auth',
)

@google_auth.tokengetter
def google_oauth_token(token=None):
    return session.get('google_token')

###########
# Helpers #
###########

def check_oauth_token(scopes=None):
    """ Check the request for OAuth creds.
    Requires: Flask Request and access_token in request.args
    Return Token or None
    """
    if scopes is None:
        scopes = []
    # Check with local OAuth Provider for user
    valid, req = oauth_provider.verify_request(scopes)
    if valid:
        return req

def user_from_email(email):
    """Get a User with the given email, or create one."""
    user = User.lookup(email)
    if not user:
        logger.info("Creating user {}".format(email))
        user = User(email=email)
        db.session.add(user)
        db.session.commit()
    return user

def google_oauth_request(token):
    """ Use fallback of Google Plus Endpoint Profile Info.
    """

@cache.memoize(timeout=600)
def google_user_data(token, timeout=5):
    """ Query google for a user's info. """
    if not token:
        logger.info("Google Token is None")
        return None
    google_plus_endpoint = "https://www.googleapis.com/plus/v1/people/me?access_token={}"

    try:
        r = requests.get(google_plus_endpoint.format(token), timeout=timeout)
        data = r.json()
        if 'error' not in data and data.get('emails'):
            user_email = data['emails'][0]['value']
            return {'email': user_email}
    except requests.exceptions.Timeout as e:
        logger.error("Timed out when using google+")
        return None

    # If Google+ didn't work - fall back to OAuth2
    oauth2_endpoint = "https://www.googleapis.com/oauth2/v3/userinfo?access_token={}"

    try:
        r = requests.get(oauth2_endpoint.format(token), timeout=timeout)
        data = r.json()
        if r.status_code != 200:
            logger.error("Google returned non 200 status code: {}", r.status_code)
        return data
    except requests.exceptions.Timeout as e:
        logger.error("Timed out when using google oauth2")
        return None

    logger.warning("None of the endpoints returned an access token.")
    return None

def user_from_google_token(token):
    """
    Get a User with the given Google access token, or create one if no User with
    this email is found. If the token is invalid, return None.
    """
    if not token:
        return None
    if use_testing_login() and token == "test":
        return user_from_email("okstaff@okpy.org")
    user_data = google_user_data(token)

    if not user_data or 'email' not in user_data:
        cache.delete_memoized(google_user_data, token)
        logger.warning("Could not login with oauth. Trying again - {}".format(user_data))
        user_data = google_user_data(token, timeout=10)

    if not user_data or 'email' not in user_data:
        cache.delete_memoized(google_user_data, token)
        logger.warning("Auth Retry failed for token {} - {}".format(token, user_data))
        return None

    return user_from_email(user_data['email'])

login_manager = LoginManager()

@login_manager.user_loader
def load_user(userid):
    return User.get_by_id(userid)

@login_manager.request_loader
def load_user_from_request(request):
    """ For the API routes to allow login via access_token.
    """
    if request.blueprint != "api":
        return None
    # Checks for bearer token in header authentication
    oauth_token = check_oauth_token()
    if oauth_token:
        oauth_token.user.scopes = oauth_token.access_token.scopes
        return oauth_token.user

@login_manager.unauthorized_handler
def unauthorized():
    session['after_login'] = request.url
    login_hint = request.args.get('login_hint')
    return redirect(url_for('auth.login', login_hint=login_hint))

def authorize_user(user):
    if user is None:
        logger.error("Google Auth Failure - attempting to authorize None user")
        raise TypeError("Cannot login as None")
    login_user(user)
    after_login = session.pop('after_login', None)
    return redirect(after_login or url_for('student.index'))

def use_testing_login():
    """
    Return True if we use the unsecure testing login instead of Google OAuth.
    Requires TESTING_LOGIN = True in the config and the environment is not prod.
    """
    return (current_app.config.get('TESTING_LOGIN', False) and
            current_app.config.get('ENV') != 'prod')

def csrf_check():
    """ Manually against CSRF if available. Usually done by default, but this
    function is neccesary for routes in blueprints that have disabled csrf protection.

    CSRF protect is disabled in testing, but not in dev or prod.
    Always checks for CSRF in prod
    """
    current_env = current_app.config.get('ENV')
    csrf_enabled = current_app.config.get('WTF_CSRF_ENABLED', True)

    if current_env == 'prod' or csrf_enabled:
        csrf.protect()

@auth.route("/login/")
def login():
    """
    Authenticates a user with an access token using Google APIs.
    """
    if use_testing_login():
        return redirect(url_for('.testing_login'))
    return google_auth.authorize(
        callback=url_for('.authorized', _external=True),
        login_hint=request.args.get('login_hint'))

@auth.route('/login/authorized/')
def authorized():
    resp = google_auth.authorized_response()
    if resp is None:
        error = "Access denied: reason={0} error={1}".format(
            request.args['error_reason'],
            request.args['error_description']
        )
        flash(error, "error")
        # TODO Error Page
        return redirect("/")
    if isinstance(resp, OAuthException):
        error = "{0} - {1}".format(resp.data.get('error', 'Unknown Error'),
                                   resp.data.get('error_description', 'Unknown'))
        flash(error, "error")
        # TODO Error Page
        return redirect("/")

    access_token = resp['access_token']
    user = user_from_google_token(access_token)
    if not user:
        logger.warning("Attempt to get user info failed")
        flash("We could not log you in. Maybe try another email?", 'warning')
        return redirect("/")

    logger.info("Login from {}".format(user.email))
    expires_in = resp.get('expires_in', 0)
    session['token_expiry'] = dt.datetime.now() + dt.timedelta(seconds=expires_in)
    session['google_token'] = (access_token, '')  # (access_token, secret)
    return authorize_user(user)

################
# Other Routes #
################

@auth.route('/sudo/<email>/')
@login_required
def sudo_login(email):
    logger.info("Sudo attempt to %s from %s", email, current_user)
    if not current_user.is_admin:
        logger.info("Unauthorized sudo %s", current_user)
        return abort(403, 'Unauthorized to sudo')
    user = User.lookup(email)
    if not user:
        return abort(404, "User does not exist")
    logger.info("Sudo Mode: %s from %s", email, current_user)
    session['sudo-user'] = current_user.email
    return authorize_user(user)

# Backdoor log in if you want to impersonate a user.
# Will not give you a Google auth token.
# Requires that TESTING_LOGIN = True in the config and we must not be running in prod.
@auth.route('/testing-login/')
def testing_login():
    if not use_testing_login():
        abort(404)

    random_staff = utils.random_row(Enrollment.query.filter_by(role='staff'))
    if random_staff:
        random_staff = random_staff.user
    random_student = utils.random_row(Enrollment.query.filter_by(role='student'))
    if random_student:
        random_student = random_student.user
    return render_template('testing-login.html',
        callback=url_for(".testing_authorized"),
        random_admin=utils.random_row(User.query.filter_by(is_admin=True)),
        random_staff=random_staff,
        random_student=random_student,
        random_user=utils.random_row(User.query))

@auth.route('/testing-login/authorized/', methods=['POST'])
def testing_authorized():
    if not use_testing_login():
        abort(404)
    user = user_from_email(request.form['email'])
    return authorize_user(user)

@auth.route('/testing-login/logout/', methods=['POST'])
def testing_logout():
    if not use_testing_login():
        abort(404)
    logout_user()
    session.clear()
    return redirect(url_for('student.index'))

@auth.route("/logout/", methods=['POST'])
@login_required
def logout():
    # Only CSRF protect this route.
    csrf_check()

    logout_user()
    session.clear()
    return redirect(url_for('student.index'))

server/controllers/queue.py
from flask import abort, current_app
from flask_login import current_user
import rq_dashboard

from server import jobs

queue = rq_dashboard.blueprint

@queue.before_request
def authenticate(*args, **kwargs):
    if not current_user.is_authenticated:
        return current_app.login_manager.unauthorized()
    if not current_user.is_admin:
        abort(403)

server/templates/_globalhelpers.html
{% macro backup_style(backup_id) %}
    <tt>{{ backup_id }}</tt>
{% endmacro %}

server/templates/alerts.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

server/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    {% include "icons.html" %}

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Quicksand:400,700,300|Lato:300,400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" rel="stylesheet">
    {% assets "common_css" %}
      <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}" />
    {% endassets %}

    {% block css %}
    {% endblock %}
  </head>
  <body>

    {% block body %}
    {% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/markdown-it/8.0.1/markdown-it.min.js"></script>
    {% assets "common_js" %}
      <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}

    {% block js %}
    {% endblock %}

    <script type="text/javascript">
      var csrf_token = "{{ csrf_token() }}";
    </script>
  </body>
</html>

server/templates/diff.html
{# Renders a line number. If i is None then no number is displayed. #}
{% macro line_number(i) %}
  <td class="line-number" data-line-number="{{ '' if i is none else i }}"></td>
{% endmacro %}

{% macro render_comment(comment) %}
  <div class="comment"
    id="{{ utils.encode_id(comment.id) }}" 
    data-id="{{ utils.encode_id(comment.id) }}"
    data-message="{{ comment.message }}"
    data-no-instant>
    <div class="comment-header clearfix">
      <div class="comment-author">
        {{ comment.author.email }} commented {{ utils.natural_time(comment.created) }}
      </div>
      {% if comment.author == current_user or current_user.is_admin %}
      <div class="comment-actions">
        <button class="btn btn-link comment-action comment-edit"><i class="fa fa-pencil"></i></button>
        <button class="btn btn-link comment-action comment-delete"><i class="fa fa-times"></i></button>
      </div>
      {% endif %}
    </div>
    <div class="comment-body markdown-body">{{ comment.message | markdown }}</div>
  </div>
{% endmacro %}

{% macro editor_template() %}
  <div class="comment comment-editor clearfix">
    <div class="comment-write">
      <textarea placeholder="Leave a comment" rows="8"></textarea>
    </div>
    <div class="comment-preview">
      <div class="comment-body markdown-body"></div>
    </div>
    <div class="comment-editor-actions">
      <button class="btn btn-default comment-cancel">Cancel</button>
      <button class="btn btn-primary comment-save">Save</button>
    </div>
  </div>
{% endmacro %}

{% macro source_file(backup, filename, file) %}
  <div class="source-file table-responsive"
    data-backup-id={{ utils.encode_id(backup.id) }}
    data-filename={{ filename }}>
    <table class="highlight">
      <thead>
        <tr>
          <th class="source-file-header" colspan=3>
              <div class="source-file-name fixed-width-font">{{ filename }}</div>
              <a data-no-instant href="{{ url_for('student.download', name=backup.assignment.name, submit=backup.submit, bid=backup.id, file=filename) }}"
              class="no-dash dl-button source-file-download">
                  <i class="fa fa-download"></i> Download
              </a>
              <a data-no-instant href="{{ url_for('student.download', name=backup.assignment.name, submit=backup.submit, bid=backup.id, file=filename, raw=1) }}"
              class="no-dash dl-button source-file-download">
                  <i class="fa fa-eye"></i> Raw
              </a>
          </th>
        </tr>
        {% if file.too_big %}
        <tr>
          <th class="file-blob" colspan=3>
              <a data-no-instant href="{{ url_for('student.download', name=backup.assignment.name, submit=backup.submit, bid=backup.id, file=filename, raw=1) }}">
                View Raw File
              </a>
              <h6>This file is too large to display</h6>
          </th>
        </tr>
        {% endif %}
      </thead>
      <tbody>
        {% for line in file.lines %}
          <tr class="fixed-width-font highlight-{{ line.tag }}" data-line={{ line.line_after }}>
            {% if line.is_diff %}
              {{ line_number(line.line_before) }}
            {% endif %}
            {{ line_number(line.line_after) }}
            <td>
              {% if line.line_after %}
                <span class="comment-add"><i class="fa fa-plus"></i></span>
              {% endif %}
              <span class="highlight-source">{{ line.contents | safe }}</span>
            </td>
          </tr>
          {% if line.comments %}
            <tr data-line={{ line.line_after }}>
              <td class="comment-container" colspan=3>
                {% for comment in line.comments %}
                  {{ render_comment(comment) }}
                {% endfor %}
              </td>
            </tr>
          {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endmacro %}

server/templates/footer.html
    <footer class="footer col-xs-12">
      <div class="col-xs-12 col-sm-4">
        <ul class="nav nav-pills nav-justified">
          <li>
            <a href="https://okpy.github.io/documentation">Documentation</a>
          </li>
        </ul>
      </div>
      <div class="col-xs-12 col-sm-4">
        <ul class="nav nav-pills nav-justified">
          <li>
            <a href="https://github.com/Cal-CS-61A-Staff/ok">GitHub Repo</a>
          </li>
        </ul>
      </div>
      <div class="col-xs-12 col-sm-4">
        <ul class="nav nav-pills nav-justified">
          <li>
            <a href="{{ url_for('about.privacy') }}">Privacy Policy</a>
          </li>
        </ul>
      </div>
    </footer>

server/templates/index.html
{% extends "about/base.html" %}

{% block title %}OK{% endblock %}

{% block content %}
<div class="landing row">
  <div class="col-md-10 col-md-offset-1">
    {% include 'alerts.html' %}
    <h1 class="title">Automate Grading &amp; Personalize Feedback.</h1>
    <p>OK autogrades programming assignments, facilitates submission, <br> composition feedback, and analytics for your class.</p>
    {% if config['TESTING_LOGIN'] and (config['ENV'] == 'dev' or config['ENV'] == 'test') %}
      <a data-no-instant href="{{ url_for('auth.testing_login') }}" id="testing-login" class="button">Testing Login</a>
    {% else %}
      <a data-no-instant href="{{ url_for('auth.login') }}" id="login" class="button">Student Login</a>
    {% endif %}
  </div>
</div>

<div class="landing row feature-block logo-section">
    <hr>
     <h2>Used by courses with millions of submissions</h2>

    <div class="col-md-10 col-md-offset-1">

        <div class="col-sm-3">
            <img class="landing-logo desaturate select-none" src="{{ url_for('static', filename='img/berkeley.png') }}">
        </div>
        <div class="col-sm-3 hidden-xs">
            <a href="http://cs61a.org" target="_blank" >
                <p class="landing-course-name"> CS 61A </p>
            </a>
        </div>
        <div class="col-sm-3 hidden-xs">
            <a href="http://data8.org/" target="_blank" >
                <p class="landing-course-name"> Data Science 8 </p>
            </a>
        </div>
        <div class="col-sm-3 hidden-xs">
            <a href="http://cs168.io" target="_blank" >
                <p class="landing-course-name"> CS 168 </p>
            </a>
        </div>
    </div>
</div>

<div class="landing row feature-block">
    <div class="col-md-6" >
        <img class="img-responsive select-none" src="{{ url_for('static', filename='img/landing-comments.png') }}">
    </div>
    <div class="col-md-6 center">
        <h1>Personalized feedback</h1>
        <p>View student solutions and leave comments on how to improve their style. You can put the pen & paper away and digitize feedback.</p>
    </div>
</div>

<div class="landing row feature-block">
    <div class="col-md-6 col-md-push-6">
        <img class="img-responsive select-none" src="{{ url_for('static', filename='img/landing-stats.png') }}">
    </div>
    <div class="col-md-6 col-md-pull-6 center">
        <h1>Realtime assignment statistics</h1>
        <p> Find out what questions students are working on, how many students are done, and which students have not started with detailed statistics.</p>
    </div>
</div>

<div class="landing row feature-block">
    <div class="col-md-6">
        <img class="img-responsive select-none" src="{{ url_for('static', filename='img/landing-autograde.png') }}">
    </div>
    <div class="col-md-6 center">
        <h1>Grading with one click</h1>
        <p>With a language agnostic autograder, you can grade your assignments by simply specifying a command to run. We'll handle the infrastructure so you can focus on teaching.</p>
        <p>OK features plagarism detection that will flag submissions that are plagarized from another student or somewhere on the internet.</p>
    </div>
</div>

<div class="landing row">
    <hr>

    <div class="col-md-12">
        <h2>Learn more about how OK can streamline your course.</h2>
        <p> OK is an suite of open source software tools to developed to support computer science courses. <br> Contact us to see how OK can help streamline assignment submissions.  </p>
        <a href="mailto://cs61a@berkeley.edu?cc=denero@berkeley.edu&bcc=sumukh@berkeley.edu&subject=Using%20OK" class="button">Contact us</a>
    </div>
</div>

{% endblock content %}

server/templates/testing-login.html
{% extends "staff/base.html" %}

{% block title %}Login for Testing{% endblock %}

{% macro testing_login_button(user, type) %}
    {% if user %}
        <div class="login-box-body">
            <p class="login-box-msg">Impersonate a random {{ type }}</p>
            <form action="{{ callback }}" method="post">
                <input type="hidden" value="{{ user.email }}" class="form-control" name="email" placeholder="Email">
                <div class="row">
                    <button type="submit" id="{{type}}" class="btn btn-primary btn-block btn-flat">Sign in as {{ user.email }}</button>
                </div>
            </form>
        </div>
    {% endif %}
{% endmacro %}

{% block body %}
    <div class="login-box">
        <div class="login-logo">
            Login for Testing
        </div>
        {{ testing_login_button(random_student, 'student') }}
        {{ testing_login_button(random_staff, 'staff') }}
        {{ testing_login_button(random_user, 'user') }}
        {{ testing_login_button(random_admin, 'admin') }}
        <div class="login-box-body">
            <p class="login-box-msg">Impersonate a specific user</p>
            <form action="{{ callback }}" method="post">
                <div class="form-group has-feedback">
                    <input type="text" class="form-control" name="email" id="email-login" placeholder="Email">
                </div>
                <div class="row">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}